// Component templates for export
// These are simplified versions that work standalone

export function generatePackageJson(): string {
  return JSON.stringify({
    name: 'custom-component-library',
    version: '1.0.0',
    description: 'Custom React component library generated by Component Library Customizer',
    main: './dist/index.js',
    module: './dist/index.esm.js',
    types: './dist/index.d.ts',
    files: [
      'dist',
      'styles'
    ],
    exports: {
      '.': {
        import: './dist/index.esm.js',
        require: './dist/index.js',
        types: './dist/index.d.ts'
      },
      './styles': {
        import: './styles/tokens.css',
        require: './styles/tokens.css'
      }
    },
    author: 'Your Name',
    license: 'MIT',
    keywords: [
      'react',
      'components',
      'design-system',
      'ui-library',
      'typescript'
    ],
    scripts: {
      build: 'vite build',
      'type-check': 'tsc --noEmit'
    },
    peerDependencies: {
      react: '^18.0.0 || ^19.0.0',
      'react-dom': '^18.0.0 || ^19.0.0'
    },
    dependencies: {
      'lucide-react': '^0.460.0'
    },
    devDependencies: {
      '@types/react': '^18.0.0 || ^19.0.0',
      '@types/react-dom': '^18.0.0 || ^19.0.0',
      '@vitejs/plugin-react': '^4.0.0',
      typescript: '^5.0.0',
      vite: '^5.0.0',
      'vite-plugin-dts': '^3.0.0'
    },
    repository: {
      type: 'git',
      url: 'https://github.com/therealkishorekumar/custom-component-library'
    },
    bugs: {
      url: 'https://github.com/therealkishorekumar/custom-component-library/issues'
    },
    homepage: 'https://github.com/therealkishorekumar/custom-component-library#readme'
  }, null, 2);
}

export function generateReadme(componentNames: string[]): string {
  return `# Custom Component Library

A React component library with custom design tokens.

## Installation

\`\`\`bash
npm install
\`\`\`

## Usage

### Option 1: Import the built library

\`\`\`tsx
import { Button, Input, Card } from 'custom-component-library';
import 'custom-component-library/styles/tokens.css';

function App() {
  return (
    <Card>
      <Input label="Name" placeholder="Enter your name" />
      <Button variant="primary">Submit</Button>
    </Card>
  );
}
\`\`\`

### Option 2: Use in your project directly

Copy the files to your project:

\`\`\`bash
cp -r component-library/* src/components/
\`\`\`

Then import:

\`\`\`tsx
import { Button, Input, Card } from './components';
import './components/styles/tokens.css';
import './components/styles/reset.css';
\`\`\`

## Theme Toggle

To enable dark mode, add the \`data-theme="dark"\` attribute to your HTML element:

\`\`\`tsx
<html data-theme="dark">
\`\`\`

Or toggle dynamically:

\`\`\`tsx
document.documentElement.setAttribute('data-theme', 'dark');
// or
document.documentElement.setAttribute('data-theme', 'light');
\`\`\`

## Available Components

${componentNames.map(name => `- **${name}**`).join('\n')}

## Customization

Edit \`styles/tokens.css\` to customize the design tokens. The CSS uses CSS custom properties (variables) that can be overridden:

\`\`\`css
:root {
  --semantic-accent-primary: #your-color;
  --semantic-surface-primary: #your-color;
  /* etc... */
}
\`\`\`

## Development

\`\`\`bash
# Install dependencies
npm install

# Build the library
npm run build

# Type check
npm run type-check
\`\`\`

## License

MIT

---
Generated by [Component Library Customizer](https://therealkishorekumar.github.io/react-lib/)
`;
}

export function generateIndexTs(componentNames: string[]): string {
  return `// Component Library Index
// Generated by Component Library Customizer

${componentNames.map(name => `export * from './components/${name}';`).join('\n')}
`;
}

export function generateViteConfig(): string {
  return `import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import dts from 'vite-plugin-dts';
import { resolve } from 'path';

export default defineConfig({
  plugins: [
    react(),
    dts({
      insertTypesEntry: true,
    }),
  ],
  build: {
    lib: {
      entry: resolve(__dirname, 'index.ts'),
      name: 'CustomComponentLibrary',
      formats: ['es', 'umd'],
      fileName: (format) => \`index.\${format === 'es' ? 'esm' : format}.js\`,
    },
    rollupOptions: {
      external: ['react', 'react-dom', 'lucide-react'],
      output: {
        globals: {
          react: 'React',
          'react-dom': 'ReactDOM',
          'lucide-react': 'lucideReact',
        },
      },
    },
    cssCodeSplit: false,
  },
});
`;
}

export function generateExampleHtml(componentNames: string[]): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Component Library Preview</title>
  <link rel="stylesheet" href="./styles/tokens.css">
  <link rel="stylesheet" href="./styles/reset.css">
  <style>
    body {
      padding: 2rem;
      background: var(--semantic-surface-primary);
      color: var(--semantic-content-primary);
    }
    .demo-section {
      margin-bottom: 2rem;
      padding: 1.5rem;
      background: var(--semantic-surface-secondary);
      border-radius: var(--radius-surface);
      border: 1px solid var(--semantic-border);
    }
    .demo-title {
      margin-bottom: 1rem;
      font-size: var(--font-size-lg);
      font-weight: var(--font-weight-semibold);
    }
    .demo-row {
      display: flex;
      flex-wrap: wrap;
      gap: 1rem;
      align-items: center;
    }
  </style>
</head>
<body>
  <h1>Component Library Preview</h1>
  <p>This is a preview of your exported component library. Open the browser console to see available components.</p>
  
  <div class="demo-section">
    <div class="demo-title">Available Components</div>
    <div class="demo-row">
      ${componentNames.map(name => `<code>&lt;${name} /&gt;</code>`).join('\n      ')}
    </div>
  </div>

  <div class="demo-section">
    <div class="demo-title">Theme Toggle</div>
    <button onclick="toggleTheme()">Toggle Dark Mode</button>
  </div>

  <script>
    // Component names available in this library
    const components = ${JSON.stringify(componentNames, null, 2)};
    console.log('Available components:', components);
    
    // Theme toggle
    function toggleTheme() {
      const current = document.documentElement.getAttribute('data-theme');
      const next = current === 'dark' ? 'light' : 'dark';
      document.documentElement.setAttribute('data-theme', next);
      localStorage.setItem('theme', next);
    }
    
    // Restore theme
    const saved = localStorage.getItem('theme');
    if (saved) {
      document.documentElement.setAttribute('data-theme', saved);
    }
  </script>
</body>
</html>
`;
}

export function generateGitIgnore(): string {
  return `# Dependencies
node_modules
.pnp
.pnp.js

# Build outputs
dist
dist-ssr
*.local

# Editor directories and files
.vscode/*
!.vscode/extensions.json
.idea
.DS_Store
*.suo
*.ntvs*
*.njsproj
*.sln
*.sw?

# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*
lerna-debug.log*

# Testing
coverage

# Misc
*.tgz
`;
}
