// Component templates for export
// These are simplified versions that work standalone

export function generatePackageJson(): string {
  return JSON.stringify({
    name: 'custom-component-library',
    version: '1.0.0',
    description: 'Custom React component library generated by Component Library Customizer',
    main: 'index.ts',
    types: 'index.ts',
    author: 'Your Name',
    license: 'MIT',
    keywords: [
      'react',
      'components',
      'design-system',
      'ui-library',
      'typescript'
    ],
    scripts: {
      build: 'tsc',
      'type-check': 'tsc --noEmit'
    },
    peerDependencies: {
      react: '^18.0.0 || ^19.0.0',
      'react-dom': '^18.0.0 || ^19.0.0'
    },
    dependencies: {
      'lucide-react': '^0.263.0'
    },
    devDependencies: {
      typescript: '^5.0.0',
      '@types/react': '^18.0.0 || ^19.0.0',
      '@types/react-dom': '^18.0.0 || ^19.0.0'
    },
    repository: {
      type: 'git',
      url: 'https://github.com/therealkishorekumar/custom-component-library'
    },
    bugs: {
      url: 'https://github.com/therealkishorekumar/custom-component-library/issues'
    }
  }, null, 2);
}

export function generateReadme(componentNames: string[]): string {
  const componentList = componentNames.map(name => `- **${name}**: A short description of the ${name} component.`).join('\n');

  return `# Custom Component Library

A React component library with custom design tokens.

## Installation

\`\`\`bash
npm install
\`\`\`

## Usage (local)

\`\`\`tsx
import { ${componentNames.join(', ')} } from './index';
import './styles/tokens.css';
import './styles/reset.css';

function App() {
  return (
    <div>
      <Button variant="primary">Click Me</Button>
      <Input label="Name" placeholder="Enter name..." />
      <Badge variant="success">Active</Badge>
    </div>
  );
}
\`\`\`

## Usage (as a package)

\`\`\`tsx
import { ${componentNames.join(', ')} } from 'custom-component-library';
import 'custom-component-library/styles/tokens.css';
import 'custom-component-library/styles/reset.css';
\`\`\`

## Components

${componentList}

## Customization

Edit \`styles/tokens.css\` to customize the design tokens.

---
Generated by Component Library Customizer
`;
}

export function generateIndexTs(componentNames: string[]): string {
  return `// Component Library Index
${componentNames.map(name => `export * from './components/${name}';`).join('\n')}
`;
}
