import { DesignTokens } from '../types/tokens';
import { buildGoogleFontsUrl } from './fonts';

export function generateTokensCSS(tokens: DesignTokens): string {
  const lines: string[] = [
    '/* Design Tokens - Generated by Component Library Customizer */',
  ];

  const fontUrl = buildGoogleFontsUrl([
    tokens.typography.fontFamily,
    tokens.typography.fontFamilyMono,
  ]);

  if (fontUrl) {
    lines.push(`@import url('${fontUrl}');`, '');
  }

  lines.push(
    '',
    ':root {',
    '  /* Light Theme Colors (default) */'
  );

  // Light Theme Colors
  Object.entries(tokens.lightTheme).forEach(([key, value]) => {
    const cssKey = key.replace(/([A-Z])/g, '-$1').toLowerCase();
    lines.push(`  --color-${cssKey}: ${value};`);
  });

  // Typography
  lines.push('');
  lines.push('  /* Typography */');
  lines.push(`  --font-family: ${tokens.typography.fontFamily};`);
  lines.push(`  --font-family-mono: ${tokens.typography.fontFamilyMono};`);
  lines.push(`  --font-size-xs: ${tokens.typography.fontSizeXs};`);
  lines.push(`  --font-size-sm: ${tokens.typography.fontSizeSm};`);
  lines.push(`  --font-size-md: ${tokens.typography.fontSizeMd};`);
  lines.push(`  --font-size-lg: ${tokens.typography.fontSizeLg};`);
  lines.push(`  --font-size-xl: ${tokens.typography.fontSizeXl};`);
  lines.push(`  --font-weight-normal: ${tokens.typography.fontWeightNormal};`);
  lines.push(`  --font-weight-medium: ${tokens.typography.fontWeightMedium};`);
  lines.push(`  --font-weight-semibold: ${tokens.typography.fontWeightSemibold};`);
  lines.push(`  --font-weight-bold: ${tokens.typography.fontWeightBold};`);
  lines.push(`  --line-height-tight: ${tokens.typography.lineHeightTight};`);
  lines.push(`  --line-height-normal: ${tokens.typography.lineHeightNormal};`);
  lines.push(`  --line-height-relaxed: ${tokens.typography.lineHeightRelaxed};`);

  // Spacing
  lines.push('');
  lines.push('  /* Spacing */');
  Object.entries(tokens.spacing).forEach(([key, value]) => {
    lines.push(`  --spacing-${key}: ${value};`);
  });

  // Border Radius
  lines.push('');
  lines.push('  /* Border Radius */');
  Object.entries(tokens.borderRadius).forEach(([key, value]) => {
    lines.push(`  --radius-${key}: ${value};`);
  });

  // Shadows
  lines.push('');
  lines.push('  /* Shadows */');
  Object.entries(tokens.shadows).forEach(([key, value]) => {
    lines.push(`  --shadow-${key}: ${value};`);
  });

  // Transitions
  lines.push('');
  lines.push('  /* Transitions */');
  Object.entries(tokens.transitions).forEach(([key, value]) => {
    lines.push(`  --transition-${key}: ${value};`);
  });

  // Effects
  lines.push('');
  lines.push('  /* Effects */');
  lines.push(`  --focus-ring-width: ${tokens.effects.focusRingWidth};`);
  lines.push(`  --focus-ring-offset: ${tokens.effects.focusRingOffset};`);
  lines.push(`  --focus-ring-color: ${tokens.effects.focusRingColor};`);
  lines.push(`  --shadow-color: ${tokens.effects.shadowColor};`);

  // Patterns
  const patternColor = `color-mix(in srgb, var(--color-text) ${Math.round(tokens.patterns.background.opacity * 100)}%, transparent)`;
  const surfacePatternColor = `color-mix(in srgb, var(--color-text) ${Math.round(tokens.patterns.surface.opacity * 100)}%, transparent)`;
  const patternImage = (type: 'none' | 'dots' | 'grid' | 'plus', color: string) => {
    if (type === 'dots') {
      return `radial-gradient(circle, ${color} 1px, transparent 1px)`;
    }
    if (type === 'grid') {
      return `linear-gradient(${color} 1px, transparent 1px), linear-gradient(90deg, ${color} 1px, transparent 1px)`;
    }
    if (type === 'plus') {
      return `linear-gradient(${color} 1px, transparent 1px), linear-gradient(90deg, ${color} 1px, transparent 1px), radial-gradient(circle, ${color} 1px, transparent 1px)`;
    }
    return 'none';
  };
  lines.push('');
  lines.push('  /* Patterns */');
  lines.push(`  --pattern-background-image: ${patternImage(tokens.patterns.background.type, patternColor)};`);
  lines.push(`  --pattern-background-size: ${tokens.patterns.background.size}px ${tokens.patterns.background.size}px;`);
  lines.push(`  --pattern-surface-image: ${patternImage(tokens.patterns.surface.type, surfacePatternColor)};`);
  lines.push(`  --pattern-surface-size: ${tokens.patterns.surface.size}px ${tokens.patterns.surface.size}px;`);

  // Components
  lines.push('');
  lines.push('  /* Component Styles */');
  Object.entries(tokens.components).forEach(([component, props]) => {
    Object.entries(props).forEach(([key, value]) => {
      const cssKey = key.replace(/([A-Z])/g, '-$1').toLowerCase();

      // Special handling for focus ring alpha - convert to color-mix
      if (key === 'focusRingAlpha') {
        const percentage = Math.round((value as number) * 100);
        lines.push(`  --${component}-focus-ring-color: color-mix(in srgb, var(--color-primary) ${percentage}%, transparent);`);
      }
      // Special handling for elevated border - only apply if enabled
      else if (key === 'elevatedBorderWidth') {
        const enabled = (tokens.components as any).card?.elevatedBorderEnabled;
        lines.push(`  --card-elevated-border-width: ${enabled ? value : '0px'};`);
      }
      // Skip elevatedBorderEnabled as it's a control flag, not a CSS value
      else if (key === 'elevatedBorderEnabled') {
        // Skip - this is handled in elevatedBorderWidth
      }
      // Regular component properties
      else {
        lines.push(`  --${component}-${cssKey}: ${value};`);
      }
    });
  });

  lines.push('}');

  // Dark Theme
  lines.push('');
  lines.push('[data-theme="dark"] {');
  lines.push('  /* Dark Theme Colors */');
  Object.entries(tokens.darkTheme).forEach(([key, value]) => {
    const cssKey = key.replace(/([A-Z])/g, '-$1').toLowerCase();
    lines.push(`  --color-${cssKey}: ${value};`);
  });
  lines.push('}');

  return lines.join('\n');
}

export function generateResetCSS(): string {
  return `/* Minimal CSS Reset */

*, *::before, *::after {
  box-sizing: border-box;
}

* {
  margin: 0;
}

html {
  -webkit-text-size-adjust: 100%;
}

body {
  font-family: var(--font-family);
  line-height: var(--line-height-normal);
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

img, picture, video, canvas, svg {
  display: block;
  max-width: 100%;
}

input, button, textarea, select {
  font: inherit;
}

p, h1, h2, h3, h4, h5, h6 {
  overflow-wrap: break-word;
}
`;
}
